import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>LearnToBuild | Find the best resources</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div>
          <h1>Learn To Build</h1>
          <h1>Make your Learning journey faster</h1>
        </div>
      </main>

    </div>
  )
}
